version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files
      - ../docker-data/pcache-cron.log:/var/www/scripts/nohup.out

      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/common/location.php:/var/www/html/protected/application/themes/BaseV1/layouts/parts/singles/location.php
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d

      # themes and plugins
      - ../themes/MapasPA:/var/www/html/protected/application/themes/MapasPA
      - ../plugins/AldirBlanc:/var/www/html/protected/application/plugins/AldirBlanc
      - ../plugins/AldirBlancDataprev:/var/www/html/protected/application/plugins/AldirBlancDataprev
      - ../plugins/AldirBlancPreDataprev:/var/www/html/protected/application/plugins/AldirBlancPreDataprev
      - ../plugins/AldirBlancRedirects:/var/www/html/protected/application/plugins/AldirBlancRedirects
      - ../plugins/AldirBlancValidador:/var/www/html/protected/application/plugins/AldirBlancValidador
      - ../plugins/AldirBlancValidadorFinanceiro:/var/www/html/protected/application/plugins/AldirBlancValidadorFinanceiro
      - ../plugins/AldirBlancValidadorRecurso:/var/www/html/protected/application/plugins/AldirBlancValidadorRecurso
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth
      - ../plugins/RegistrationPayments:/var/www/html/protected/application/plugins/RegistrationPayments
      - ../plugins/SettingsPa:/var/www/html/protected/application/plugins/SettingsPa
      - ../compose/common/lgpd-terms:/var/www/html/protected/application/conf/lgpd-terms
      - ../compose/common/agent-form-1.php:/var/www/html/protected/application/themes/BaseV1/layouts/parts/singles/agent-form-1.php
      - ../compose/common/agent-form-2.php:/var/www/html/protected/application/themes/BaseV1/layouts/parts/singles/agent-form-2.php


    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - JOBS_INTERVAL=10
      
      - APP_MODE=development
      - REDIS_CACHE=redis
    depends_on:
      - db
      - redis

    stdin_open: true
    tty: true

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ../docker-data/db-data:/var/lib/postgresql/data

volumes:
  db-data:
